version: '3.7'

services:
  db:
    container_name: 'postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - backend/.env
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    command: -p 5432 -c idle_session_timeout=600000
    networks:
      - app-network

  #frontend:
  #  build:
  #    context: frontend
  #  container_name: front
  #  networks:
  #    - app-network

  backend:
    build:
      context: backend
    env_file:
      - backend/.env
    container_name: fastapi_app
    command: ["/code/docker_scripts/app_run.sh"]
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    restart: "always"
    build:
      context: nginx
    volumes:
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      #- frontend
    ports:
      - "80:80"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=antonow.artyom@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0  # чтобы не было косяков с nginx лушче в одну сеть с app
      - PGADMIN_LISTEN_PORT=5555
    networks:
      - app-network

networks:
  app-network:
