"""empty message

Revision ID: 9fe236385356
Revises: 9da2f1cee61c
Create Date: 2023-11-25 17:40:52.287829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fe236385356'
down_revision = '9da2f1cee61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Places__id'), 'Places', ['id'])
    op.create_unique_constraint(op.f('uq__payment__id'), 'payment', ['id'])
    op.add_column('payment_method', sa.Column('method_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(op.f('uq__payment_method__id'), 'payment_method', ['id'])
    op.create_unique_constraint(op.f('uq__payment_method__method_id'), 'payment_method', ['method_id'])
    op.create_unique_constraint(op.f('uq__reservations__id'), 'reservations', ['id'])
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq__reservations__id'), 'reservations', type_='unique')
    op.drop_constraint(op.f('uq__payment_method__method_id'), 'payment_method', type_='unique')
    op.drop_constraint(op.f('uq__payment_method__id'), 'payment_method', type_='unique')
    op.drop_column('payment_method', 'method_id')
    op.drop_constraint(op.f('uq__payment__id'), 'payment', type_='unique')
    op.drop_constraint(op.f('uq__Places__id'), 'Places', type_='unique')
    # ### end Alembic commands ###
