"""empty message

Revision ID: 765fc9095086
Revises: 0e7437e1db8b
Create Date: 2023-11-26 08:28:52.166533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765fc9095086'
down_revision = '0e7437e1db8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
