"""empty message

Revision ID: dfbc035f58de
Revises: 43232c86fe88
Create Date: 2023-11-25 16:30:43.393624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbc035f58de'
down_revision = '43232c86fe88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Places', sa.Column('street_name', sa.TEXT(), nullable=True))
    op.create_unique_constraint(op.f('uq__Places__id'), 'Places', ['id'])
    op.create_unique_constraint(op.f('uq__payment__id'), 'payment', ['id'])
    op.create_unique_constraint(op.f('uq__payment_method__id'), 'payment_method', ['id'])
    op.create_unique_constraint(op.f('uq__reservations__id'), 'reservations', ['id'])
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq__reservations__id'), 'reservations', type_='unique')
    op.drop_constraint(op.f('uq__payment_method__id'), 'payment_method', type_='unique')
    op.drop_constraint(op.f('uq__payment__id'), 'payment', type_='unique')
    op.drop_constraint(op.f('uq__Places__id'), 'Places', type_='unique')
    op.drop_column('Places', 'street_name')
    # ### end Alembic commands ###
