"""empty message

Revision ID: 598e3eb267e5
Revises: 
Create Date: 2023-11-24 05:11:50.085984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '598e3eb267e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cities',
    sa.Column('city_name', sa.TEXT(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('city_name', 'city_id', name=op.f('pk__Cities')),
    sa.UniqueConstraint('city_id', name=op.f('uq__Cities__city_id')),
    sa.UniqueConstraint('city_name', name=op.f('uq__Cities__city_name'))
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
    sa.UniqueConstraint('email', name=op.f('uq__user__email')),
    sa.UniqueConstraint('id', name=op.f('uq__user__id'))
    )
    op.create_index(op.f('ix__user__password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix__user__username'), 'user', ['username'], unique=True)
    op.create_table('Places',
    sa.Column('City', sa.TEXT(), nullable=False),
    sa.Column('City_id', sa.INTEGER(), nullable=False),
    sa.Column('parking_address', sa.TEXT(), nullable=False),
    sa.Column('number_of_place', sa.INTEGER(), nullable=False),
    sa.Column('time_occupied_from', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_occupied_to', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['City_id'], ['Cities.city_id'], name=op.f('fk__Places__City_id__Cities')),
    #sa.PrimaryKeyConstraint('City', name=op.f('pk__Places')),
    postgresql_partition_by='LIST ("City_id")'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Places')
    op.drop_index(op.f('ix__user__username'), table_name='user')
    op.drop_index(op.f('ix__user__password'), table_name='user')
    op.drop_table('user')
    op.drop_table('Cities')
    # ### end Alembic commands ###
