"""empty message

Revision ID: 0e7437e1db8b
Revises: 3c890432ec64
Create Date: 2023-11-26 07:35:11.430262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7437e1db8b'
down_revision = '3c890432ec64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__reservations__parking_id', 'reservations', type_='unique')
    op.drop_constraint('uq__reservations__user_id', 'reservations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq__reservations__user_id', 'reservations', ['user_id'])
    op.create_unique_constraint('uq__reservations__parking_id', 'reservations', ['parking_id'])
    # ### end Alembic commands ###
