"""empty message

Revision ID: 4cacf6bec948
Revises: ece8cc0c179c
Create Date: 2023-11-25 19:00:33.433701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cacf6bec948'
down_revision = 'ece8cc0c179c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Places', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('Places', 'type_of_parking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Places', sa.Column('type_of_parking', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('Places', 'description')
    # ### end Alembic commands ###
